swagger: '2.0'
info:
  version: '1.0'
  title: Toddle Assignment
  description: 'CRUD Apis of Users and Surveys'
  contact: {}
host: 'arcane-falls-01320.herokuapp.com'
basePath: /v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /login:
    post:
      tags:
      - "Authentication"
      description: 'to get access token by providing valid credentials'
      summary: 'To get access token by providing valid credentials'
      operationId: 'login'
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/login"
      responses:
        '200':
          description: ''
          schema:
            $ref: "#/definitions/loginResponse"
        '400':
          description: 'Bad request'
          schema:
            $ref: "#/definitions/errorMessage"
  /surveys:
    get:
      tags:
      - "Surveys"
      description: 'Get survey metadata'
      summary: 'To get the details of a survey'
      operationId: 'getSurvey'
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: false
          type: string
          description: ''
          default: ''
        - name: id
          in: query
          type: string
          description: 'survey id'
      responses:
        '200':
          description: ''
          schema:
            $ref: "#/definitions/getSurveyResponse"
        '400':
          description: 'Bad request'
          schema:
            $ref: "#/definitions/errorMessage"
        '404':
          description: 'User not found'
        '500':
          description: 'Server error'
    post:
      tags:
      - "Surveys"
      description: 'create a Survey'
      summary: 'Create a Survey using metedata and get survey Id'
      operationId: 'createSurvey'
      parameters:
        - name: Authorization
          in: header
          required: false
          type: string
          description: ''
          default: ''
        - name: Content-Type
          in: header
          required: false
          type: string
          description: ''
          default: 'application/json'
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/surveyMetadata"
      responses:
        '200':
          description: ''
          schema:
            $ref: "#/definitions/surveyCreateResponse"
        '400':
          description: 'Bad request'
          schema:
            $ref: "#/definitions/errorMessage"
        '500':
          description: 'Server error'
  /surveys/questions:
    post:
      tags:
      - "Surveys"
      description: 'Add Survey Questions'
      summary: 'Associate a question with a survey'
      operationId: 'addSurveyQuestions'
      parameters:
        - name: Authorization
          in: header
          required: false
          type: string
          description: ''
          default: ''
        - name: Content-Type
          in: header
          required: false
          type: string
          description: ''
          default: 'application/json'
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/addSurveyQuestions"
      responses:
        '200':
          description: ''
          schema:
            $ref: "#/definitions/surveyCreateResponse"
        '400':
          description: 'Bad request'
          schema:
            $ref: "#/definitions/errorMessage"
        '500':
          description: 'Server error'
    get:
      tags:
      - "Surveys"
      description: 'Get survey questions'
      summary: 'Get all the questions of a survey'
      operationId: 'getSurveyQuestions'
      parameters:
        - name: Authorization
          in: header
          required: false
          type: string
          description: ''
          default: ''
        - name: Content-Type
          in: header
          required: false
          type: string
          description: ''
          default: 'application/json'
        - name: surveyId
          in: query
          required: true
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: "#/definitions/addSurveyQuestions"
        '400':
          description: 'Bad request'
          schema:
            $ref: "#/definitions/errorMessage"
        '500':
          description: 'Server error'
  /surveys/{surveyId}/result:
    post:
      tags:
      - "Surveys"
      description: 'Get survey result'
      summary: 'Get survey result'
      operationId: 'getSurveyResult'
      parameters:
        - name: Authorization
          in: header
          required: false
          type: string
          description: ''
          default: ''
        - name: surveyId
          in: path
          required: true
          type: string
          description: ''
          default: 'application/json'
        - name: Content-Type
          in: header
          required: false
          type: string
          description: ''
          default: 'application/json'
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/surveyResultDateQuery"
      responses:
        '200':
          description: ''
          schema:
            $ref: "#/definitions/surveyResultResponse"
        '400':
          description: 'Bad request'
          schema:
            $ref: "#/definitions/errorMessage"
        '500':
          description: 'Server error'
  /surveys/{surveyId}/response:
    post:
      tags:
      - "Surveys"
      description: 'submit a survey response'
      summary: 'Submit survey response'
      operationId: 'submitSurvey'
      parameters:
        - name: Authorization
          in: header
          required: false
          type: string
          description: ''
          default: ''
        - name: surveyId
          in: path
          required: true
          type: string
          description: ''
          default: 'application/json'
        - name: Content-Type
          in: header
          required: false
          type: string
          description: ''
          default: 'application/json'
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/surveyResponseReqBody"
      responses:
        '200':
          description: ''
          schema:
            $ref: "#/definitions/surveyCreateResponse"
        '400':
          description: 'Bad request'
          schema:
            $ref: "#/definitions/errorMessage"
        '500':
          description: 'Server error'
  /signup:
    post:
      tags:
      - "Authentication"
      description: 'sign up an user'
      summary: 'Create a new user'
      operationId: 'signUp'
      parameters:
        - name: Content-Type
          in: header
          required: false
          type: string
          description: ''
          default: 'application/json'
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/signupUser"
      responses:
        '200':
          description: ''
          schema:
            $ref: "#/definitions/signupUserResponse"
        '400':
          description: 'Bad request'
          schema:
            $ref: "#/definitions/errorMessage"
        '500':
          description: 'Server error'
definitions:
  getSurveyResponse:
    type: "object"
    properties:
      totalQuestions:
        type: "integer"
      questions:
        type: "array"
        items:
          $ref: '#/definitions/surveyQuestion'
  addSurveyQuestions:
    type: "object"
    properties:
      questions:
        type: "array"
        items:
          $ref: '#/definitions/surveyQuestion'
  surveyQuestion:
    type: "object"
    required:
    - "question"
    - "type"
    properties:
      surveyId:
        type: "string"
      question:
        type: "string"
      type:
        type: "string"
      options:
        type: "array"
        items:
          type: "string"
      canBeSkipped:
        type: "boolean"
  errorMessage:
    type: "object"
    properties:
      message:
        type: "string"
  signupUser:
    type: "object"
    properties:
      userId:
        type: "string"
      password:
        type: "string"
      email:
        type: "string"
      phone:
        type: "string"
  login:
    type: "object"
    properties:
      userId:
        type: "string"
      password:
        type: "string"
  loginResponse:
    type: "object"
    properties:
      token:
        type: "string"
      message:
        type: "string"
  surveyCreateResponse:
    type: "object"
    properties:
      message:
        type: "string"
      id:
        type: "string"
  signupUserResponse:
    type: "object"
    properties:
      message:
        type: "string"
      userId:
        type: "string"
  surveyMetadata:
    type: "object"
    properties:
      name:
        type: "string"
      category:
        type: "string"
      subject:
        type: "string"
      topic:
        type: "string"
  surveyResultDateQuery:
    type: "object"
    properties:
      values:
        type: "array"
        items:
          type: "string"
      from:
        type: "string"
      to:
        type: "string"
  surveyResponseReqBody:
    type: "object"
    properties:
      questions:
        type: "array"
        items:
          $ref: '#/definitions/surveyResponse'
  surveyResponse:
    type: "object"
    required:
    - "questionId"
    - "answer"
    properties:
      questionId:
        type: "string"
      answer:
        type: "string"
  surveyResultResponse:
    type: "object"
    properties:
      questions:
        type: "array"
        items:
          $ref: '#/definitions/surveyResultResponseItem'
  surveyResultResponseItem:
    type: "object"
    required:
    - "question"
    - "result"
    properties:
      question:
        type: "string"
      result:
        type: "array"
        items:
          $ref: '#/definitions/result'
  result:
    type: "object"
    required:
    - "value"
    - "percent"
    properties:
      value:
        type: "string"
      percent:
        type: "number"